# This file was generated by GoReleaser. DO NOT EDIT.
cask "keytun" do
  name "keytun"
  desc "Lightweight CLI tool that lets remote colleagues type into your terminal over a screenshare"
  homepage "https://github.com/gboston/keytun"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keytun"

  on_macos do
    on_intel do
      url "https://github.com/gboston/keytun/releases/download/v#{version}/keytun_#{version}_darwin_amd64.tar.gz"
      sha256 "6379bcd6c6037dab06e19fead659a1baa4bb927fc11f810a2aa80d88884d7e30"
    end
    on_arm do
      url "https://github.com/gboston/keytun/releases/download/v#{version}/keytun_#{version}_darwin_arm64.tar.gz"
      sha256 "40c56eeeb377e943649248d0a6d90991bd5dd50c273db719462feef13c18bc99"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gboston/keytun/releases/download/v#{version}/keytun_#{version}_linux_amd64.tar.gz"
      sha256 "9887da3574cbd0c3e9d40b6cea94b16bd1a38be028c471611bf56af88c0f1757"
    end
    on_arm do
      url "https://github.com/gboston/keytun/releases/download/v#{version}/keytun_#{version}_linux_arm64.tar.gz"
      sha256 "efbf7d3fefd37756ac649f14aceff0fea9d4b9184a75a19cebeddc2f60f29c88"
    end
  end

  # No zap stanza required
end
