# This file was generated by GoReleaser. DO NOT EDIT.
cask "keytun" do
  name "keytun"
  desc "Lightweight CLI tool that lets remote colleagues type into your terminal over a screenshare"
  homepage "https://github.com/gboston/keytun"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keytun"

  on_macos do
    on_intel do
      url "https://github.com/gboston/keytun/releases/download/v#{version}/keytun_#{version}_darwin_amd64.tar.gz"
      sha256 "18769bfed445bbf36a8d3a786783986a87a625ab4d245efe9d758275138eebd2"
    end
    on_arm do
      url "https://github.com/gboston/keytun/releases/download/v#{version}/keytun_#{version}_darwin_arm64.tar.gz"
      sha256 "8c694a11c26401ff9556c2c13b81940359542154d72c7c9f61b0926f7be3b91d"
    end
  end

  # No zap stanza required
end
