# This file was generated by GoReleaser. DO NOT EDIT.
cask "keytun" do
  name "keytun"
  desc "Lightweight CLI tool that lets remote colleagues type into your terminal over a screenshare"
  homepage "https://github.com/gboston/keytun"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keytun"

  on_macos do
    on_intel do
      url "https://github.com/gboston/keytun/releases/download/v#{version}/keytun_#{version}_darwin_amd64.tar.gz"
      sha256 "504af473256906126e99a2dd3130482bd56ee9a2f129c9e8df57c55a2cdfe61f"
    end
    on_arm do
      url "https://github.com/gboston/keytun/releases/download/v#{version}/keytun_#{version}_darwin_arm64.tar.gz"
      sha256 "dda088a18873b8bc29494e2a6cb8bc7508e66cd782fdc7975c6fdb869d63a251"
    end
  end

  # No zap stanza required
end
